
language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"

sudo: false

cache:
  directories:
    - node_modules

addons:
  postgresql: "9.4"

before_script:
  - "mysql -e 'create database sequelize_auto_test;'"
  - "psql -c 'create database sequelize_auto_test;' -U postgres"

script:
  - "npm run test-buster"

branches:
  only:
    - master

notifications:
  email:
    - me@danieldurante.com

env:
  - DB=mysql DIALECT=mysql
  - DB=mysql DIALECT=postgres
  - DB=mysql DIALECT=sqlite
